baseURL = "https://jamesrwilliams.ca"
languageCode = "en-GB"
title = "James R. Williams · Web Developer"
paginate = 10
summaryLength = 40
theme = "jamesrwilliams"
pygmentsCodeFences = true
googleAnalytics = "UA-26549429-1"
enableGitInfo = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  author = "James R. Williams"
  siteDescription = "A British web developer living in Canada. Busy closing divs and mass producing angular errors."
  blogDescription = "Home of my occasional write ups of interesting tech and things I'm working on."
  image = "/profile.jpg"

[permalinks]
    blog = "/blog/:slug/"
