baseURL = "https://jamesrwilliams.ca"
languageCode = "en-GB"
title = "James R. Williams - Web Developer"
paginate = 30
summaryLength = 40
theme = "jamesrwilliams"
pygmentsCodeFences = true
enableGitInfo = true

[params]
  author = "James R. Williams"
  siteDescription = "A British web developer living in Canada. Busy closing divs and mass producing angular errors."
  image = "https://www.gravatar.com/avatar/b2623db89a42dd363c33d1d4df39654a?s=500"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    blog = "/blog/:slug/"

[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[params.algolia]
    vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
    params = ["categories", "tags"]

[outputs]
    home = ["HTML", "RSS", "Algolia"]
