baseURL = "https://jamesrwilliams.co.uk"
languageCode = "en-GB"
title = "James R. Williams - Web Developer"
paginate = 10
summaryLength = 40
theme = "jamesrwilliams"
pygmentsCodeFences = true
googleAnalytics = ""

[params]
  author = "James R. Williams"
  description = "Web developer and a wannabe software engineer."

[permalinks]
    posts = "/:year/:month/:day/:slug/"


