baseURL = "https://jamesrwilliams.co.uk"
languageCode = "en-GB"
title = "James R. Williams - Web Developer"
paginate = 10
summaryLength = 40
theme = "jamesrwilliams"
pygmentsCodeFences = true
googleAnalytics = "UA-26549429-1"
enableGitInfo = true

[params]
  author = "James R. Williams"
  description = "A British web developer living in Canada."
  image = "/profile.jpg"

[permalinks]
    blog = "/blog/:slug/"
