baseURL = "https://jamesrwilliams.co.uk"
languageCode = "en-GB"
title = "James R. Williams"
paginate =  25
theme = "jamesrwilliams"
pygmentsCodeFences = true
googleAnalytics = ""

[params]
  author = "James R. Williams"
  description = "Web developer and a wannabe software engineer."

[permalinks]
    posts = "/:year/:month/:day/:slug/"


