baseURL = "https://jamesrwilliams.co.uk"
languageCode = "en-GB"
title = "James R. Williams"
theme = "jamesrwilliams"
pygmentsCodeFences = true

[params]
  author = "James R. Williams"
  description = "Web developer and a wannabe software engineer."

[permalinks]
    posts = "/:year/:month/:day/:slug/"

[taxonomies]
    topics = "topics"
    tag = "tags"


