# theme.toml template for a Hugo theme
name = "Jamesrwilliams"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://jamesrwilliams.co.uk"
tags = []
features = []
min_version = "0.41"

[author]
  name = "James R. Williams"
  homepage = "https://jamesrwilliams.co.uk"
